FROM node:20-bullseye

# Install zip utility
RUN apt-get update -y && \
    apt-get install -y zip && \
    apt-get clean

# Cambiar a usuario node
USER node

# Set working directory
WORKDIR /workspace

# Command to run the preparation script and set ownership
CMD set -e; \
  chmod +x /workspace/.devcontainer/scripts/prepare_deployment.sh; \
    /workspace/.devcontainer/scripts/prepare_deployment.sh; \
    chown -R ${UID:-1000}:${GID:-1000} deployment || true
