services:
  prepare_deploy:
    build:
      context: .
      dockerfile: Dockerfile.prepare-deploy
    container_name: pesv_prepare_deploy
    working_dir: /workspace
    volumes:
      - ../../:/workspace:cached
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: "https://api.investigaciongipia.com/api"
      NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: "AIzaSyBWF6HhWYNjYq4MbU_1L7w1RBOtxC1ck5A"
      OVERWRITE_ENV: "false"
      PACK_NODE_MODULES: "false"
      UID: 1000
      GID: 1000
    restart: "no"
    # Optional: limit resources
    # deploy:
    #   resources:
    #     limits:
    #       memory: 1G
    #       cpus: '0.5'
